"""add_task_plans_and_integrity_events

Revision ID: 78e21fd4becc
Revises: 00dc62eaabfc
Create Date: 2026-07-28 16:19:29.461943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e21fd4becc'
down_revision: Union[str, Sequence[str], None] = '00dc62eaabfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('plan_history', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('final_result_json', sa.JSON(), nullable=True),
    sa.Column('integrity_verdict', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_plans_task_id'), 'task_plans', ['task_id'], unique=False)
    op.create_table('integrity_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('tool_call_id', sa.Uuid(), nullable=True),
    sa.Column('detector', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrity_events_task_id'), 'integrity_events', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrity_events_task_id'), table_name='integrity_events')
    op.drop_table('integrity_events')
    op.drop_index(op.f('ix_task_plans_task_id'), table_name='task_plans')
    op.drop_table('task_plans')
    # ### end Alembic commands ###
