"""full_initial

Revision ID: e2f5161fbeee
Revises: 
Create Date: 2026-08-24 08:03:42.017269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f5161fbeee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_fingerprint', sa.String(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('linked_tz_path', sa.String(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('friend_memory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_memory_category'), 'friend_memory', ['category'], unique=False)
    op.create_table('provider_health',
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('provider_class', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'degraded', 'rate_limited', 'budget_blocked', 'offline', 'disabled', name='providerstatus'), nullable=False),
    sa.Column('failure_rate_pct', sa.Integer(), nullable=False),
    sa.Column('usage_pct', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('provider_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('is_free_tier', sa.Boolean(), nullable=True),
    sa.Column('price_prompt_usd', sa.Float(), nullable=True),
    sa.Column('price_completion_usd', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_models_provider_id'), 'provider_models', ['provider_id'], unique=False)
    op.create_table('provider_tier_hints',
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('is_free_tier', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('scheduler_jobs',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('allowed_high_risk_patterns', sa.JSON(), nullable=False),
    sa.Column('timeout_sec', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_run_status', sa.String(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_label', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'idle', 'archived', name='sessionstatus'), nullable=False),
    sa.Column('active_role', sa.String(), nullable=False),
    sa.Column('current_task_id', sa.Uuid(), nullable=True),
    sa.Column('source_trust_aggregate', sa.String(), nullable=False),
    sa.Column('last_error_code', sa.String(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['current_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills_meta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('candidate', 'active', 'archived', 'needs_adaptation', 'reference_only', 'rejected', name='skillstatus'), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('source_origin', sa.String(), nullable=False),
    sa.Column('needs_adaptation', sa.Boolean(), nullable=False),
    sa.Column('active_version', sa.String(), nullable=True),
    sa.Column('history_path', sa.String(), nullable=True),
    sa.Column('last_benchmark_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'awaiting_clarification', 'awaiting_approval', 'approved', 'in_progress', 'awaiting_attention', 'under_audit', 'needs_rework', 'done', 'done_unaudited', 'failed', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('draft_tz_md', sa.Text(), nullable=True),
    sa.Column('audit_attempt_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('delegation_depth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attention_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('task_tz_approval', 'high_risk_shell', 'budget_escalation', 'skill_update', 'cron_high_risk_exception', 'untrusted_context_override', name='attentiontype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', 'cancelled', 'superseded', name='approvalstatus'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('auditor_role', sa.String(), nullable=False),
    sa.Column('auditor_model', sa.String(), nullable=False),
    sa.Column('budget_degraded', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.Enum('pass_', 'needs_rework', 'fail_after_max_attempts', 'unaudited', name='auditverdict'), nullable=False),
    sa.Column('plan_vs_fact', sa.JSON(), nullable=False),
    sa.Column('tool_success_summary', sa.JSON(), nullable=False),
    sa.Column('missing_requirements', sa.JSON(), nullable=False),
    sa.Column('patch_suggestions', sa.JSON(), nullable=False),
    sa.Column('metrics_compared', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('source_trust', sa.Enum('trusted', 'untrusted', name='sourcetrust'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=True),
    sa.Column('compressed_out', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq_no', name='uq_message_session_seq')
    )
    op.create_table('task_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('plan_history', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('final_result_json', sa.JSON(), nullable=True),
    sa.Column('integrity_verdict', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_plans_task_id'), 'task_plans', ['task_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_version', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'ok', 'error', 'timeout', 'cancelled', 'blocked_policy', 'needs_attention', 'skipped', name='toolstatus'), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('approval_item_id', sa.Uuid(), nullable=True),
    sa.Column('source_trust_snapshot', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['approval_item_id'], ['attention_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrity_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('tool_call_id', sa.Uuid(), nullable=True),
    sa.Column('detector', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrity_events_task_id'), 'integrity_events', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrity_events_task_id'), table_name='integrity_events')
    op.drop_table('integrity_events')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_task_plans_task_id'), table_name='task_plans')
    op.drop_table('task_plans')
    op.drop_table('messages')
    op.drop_table('audit_reports')
    op.drop_table('attention_items')
    op.drop_table('tasks')
    op.drop_table('skills_meta')
    op.drop_table('sessions')
    op.drop_table('scheduler_jobs')
    op.drop_table('provider_tier_hints')
    op.drop_index(op.f('ix_provider_models_provider_id'), table_name='provider_models')
    op.drop_table('provider_models')
    op.drop_table('provider_health')
    op.drop_index(op.f('ix_friend_memory_category'), table_name='friend_memory')
    op.drop_table('friend_memory')
    op.drop_table('events')
    op.drop_table('decisions')
    op.drop_table('agent_state')
    # ### end Alembic commands ###
